# Make File
PROGNAME=mqtt_client
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_mqtt.c 

# SDK features
SDK_FEATURES = wlan sockets mqtt_client freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
