# Make File
PROGNAME=ap_mode
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = ap_mode.ttl 

# SDK features
SDK_FEATURES = 

include $(RSI_SDK_PATH)/sapi/sapi.mk
