# Make File
PROGNAME=calibration_app
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += -DRSI_CALIB_MODE_EN 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_calib_app.c 

# SDK features
SDK_FEATURES = wlan sockets freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
