# Make File
PROGNAME=battery_service
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ble_battery_service.c 

# SDK features
SDK_FEATURES = ble bluetooth 

include $(RSI_SDK_PATH)/sapi/sapi.mk
