# Make File
PROGNAME=spp_slave
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = spp_slave.ttl 

# SDK features
SDK_FEATURES = 

include $(RSI_SDK_PATH)/sapi/sapi.mk
