# Make File
PROGNAME=http_client
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_http_client_app.c 

# SDK features
SDK_FEATURES = wlan sockets http_client certificates 

include $(RSI_SDK_PATH)/sapi/sapi.mk
