# Make File
PROGNAME=mqtt
RSI_SDK_PATH = ../../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_mqtt.c 

# SDK features
SDK_FEATURES = wlan sockets certificates aws mqtt_client 

include $(RSI_SDK_PATH)/sapi/sapi.mk
