# Make File
PROGNAME=sntp_client
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_sntp_client_app.c 

# SDK features
SDK_FEATURES = wlan sockets sntp 

include $(RSI_SDK_PATH)/sapi/sapi.mk
