# Make File
PROGNAME=bt_power_save
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_bt_power_save_profile.c 

# SDK features
SDK_FEATURES = bt bluetooth sbc_audio freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
