# Make File
PROGNAME=concurrent_mode
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_concurrent_mode.c 

# SDK features
SDK_FEATURES = wlan sockets freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
