# Make File
PROGNAME=immediate_alert_client
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ble_immediate_alert_client.c 

# SDK features
SDK_FEATURES = ble bluetooth 

include $(RSI_SDK_PATH)/sapi/sapi.mk
