# Make File
PROGNAME=aws_iot_multithread
RSI_SDK_PATH = ../../../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = aws_iot_multithread.c 

# SDK features
SDK_FEATURES = wlan sockets certificates aws 

include $(RSI_SDK_PATH)/sapi/sapi.mk
