# Make File
PROGNAME=aws_device_shadow
RSI_SDK_PATH = ../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_aws_device_shadow.c 

# SDK features
SDK_FEATURES = wlan sockets certificates aws freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
