# Make File
PROGNAME=low_power_station_with_ble
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = low_power_station_with_ble.ttl 

# SDK features
SDK_FEATURES = 

include $(RSI_SDK_PATH)/sapi/sapi.mk
