# Make File
PROGNAME=wlan_throughput
RSI_SDK_PATH = ../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_throughput_app.c 

# SDK features
SDK_FEATURES = wlan sockets certificates freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
