# Make File
PROGNAME=gatt_test
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ble_gatt_test.c 

# SDK features
SDK_FEATURES = ble bluetooth 

include $(RSI_SDK_PATH)/sapi/sapi.mk
