# Make File
PROGNAME=device_shadow_logging_stats
RSI_SDK_PATH = ../../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += -DLOGGING_STATS 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = device_shadow_logging_stats.c 

# SDK features
SDK_FEATURES = wlan sockets certificates aws 

include $(RSI_SDK_PATH)/sapi/sapi.mk
