# Make File
PROGNAME=ble_white_list
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ble_whitelist.c 

# SDK features
SDK_FEATURES = ble bluetooth freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
