# Make File
PROGNAME=wlan_https_bt_spp_ble_provisioning
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = main.c rsi_ble_device_info.c rsi_ble_main_task.c rsi_spp_master_slave.c rsi_ble_subtasks.c rsi_wlan_http_s.c 

# SDK features
SDK_FEATURES = wlan ble bt bluetooth freertos sockets sbc_audio certificates http_server 

include $(RSI_SDK_PATH)/sapi/sapi.mk
