# Make File
PROGNAME=ftp_client
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ftp_client.c 

# SDK features
SDK_FEATURES = wlan sockets ftp 

include $(RSI_SDK_PATH)/sapi/sapi.mk
