# Make File
PROGNAME=fw_update_over_wifi
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = fw_update_over_wifi.ttl 

# SDK features
SDK_FEATURES = 

include $(RSI_SDK_PATH)/sapi/sapi.mk
