# Make File
PROGNAME=http_otaf
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += -DAWS_ENABLE 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_http_otaf_app.c 

# SDK features
SDK_FEATURES = wlan sockets certificates freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
