# Make File
PROGNAME=udp_server
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_udp_server.c 

# SDK features
SDK_FEATURES = wlan sockets 

include $(RSI_SDK_PATH)/sapi/sapi.mk
