# Make File
PROGNAME=update_gain_table
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_update_gain_table.c 

# SDK features
SDK_FEATURES = bt ble bluetooth sbc_audio 

include $(RSI_SDK_PATH)/sapi/sapi.mk
