# Make File
PROGNAME=connection_using_asynchronous_apis_app
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_connection_using_asynchronous_apis_app.c 

# SDK features
SDK_FEATURES = wlan sockets 

include $(RSI_SDK_PATH)/sapi/sapi.mk
