# Make File
PROGNAME=three_ssl_concurrent_client_sockets
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_three_ssl_client_sockets.c 

# SDK features
SDK_FEATURES = wlan sockets certificates freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
