# Make File
PROGNAME=bt_spp_dual_role_with_secure_pairing
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_spp_master_slave.c 

# SDK features
SDK_FEATURES = bt bluetooth sbc_audio freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
