# Make File
PROGNAME=ble_per
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = ble_per.ttl 

# SDK features
SDK_FEATURES = 

include $(RSI_SDK_PATH)/sapi/sapi.mk
