# Make File
PROGNAME=customized_root_webpage
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_customized_root_webpage.c 

# SDK features
SDK_FEATURES = wlan sockets http_server 

include $(RSI_SDK_PATH)/sapi/sapi.mk
