# Make File
PROGNAME=websocket_client
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_websocket_client_app.c 

# SDK features
SDK_FEATURES = wlan sockets certificates web_socket 

include $(RSI_SDK_PATH)/sapi/sapi.mk
