# Make File
PROGNAME=bt_per
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_bt_per.c 

# SDK features
SDK_FEATURES = bt sbc_audio bluetooth 

include $(RSI_SDK_PATH)/sapi/sapi.mk
