# Make File
PROGNAME=ble_multiconnection_gatt_test
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ble_device_info.c rsi_ble_main_task.c rsi_ble_subtasks.c main.c 

# SDK features
SDK_FEATURES = ble bluetooth freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
