# Make File
PROGNAME=firmware_update
RSI_SDK_PATH = ../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_firmware_update_app.c 

# SDK features
SDK_FEATURES = wlan sockets firmware_update freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
