# Make File
PROGNAME=embedded_mqtt
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_emb_mqtt.c 

# SDK features
SDK_FEATURES = wlan sockets mqtt_client freertos 

include $(RSI_SDK_PATH)/sapi/sapi.mk
