# Make File
PROGNAME=multicast
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_multicast_app.c 

# SDK features
SDK_FEATURES = wlan sockets multicast 

include $(RSI_SDK_PATH)/sapi/sapi.mk
