# Make File
PROGNAME=wireless_firmware_upgradation
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_wfup_app.c 

# SDK features
SDK_FEATURES = wlan sockets http_server firmware_update 

include $(RSI_SDK_PATH)/sapi/sapi.mk
