# Make File
PROGNAME=wlan_throughput_bt_spp_ble_dual_role
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ble_main_task.c rsi_ble_device_info.c rsi_spp_master_slave.c rsi_ble_subtasks.c rsi_wlan_throughput.c rsi_common_app.c rsi_lk_save.c rsi_wlan_app.c 

# SDK features
SDK_FEATURES = wlan ble bt bluetooth freertos certificates sockets sbc_audio 

include $(RSI_SDK_PATH)/sapi/sapi.mk
