# Make File
PROGNAME=enterprise_client
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_eap_connectivity.c 

# SDK features
SDK_FEATURES = wlan sockets freertos certificates 

include $(RSI_SDK_PATH)/sapi/sapi.mk
