# Make File
PROGNAME=wlan_station_ble_provisioning_AWS
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ble_app.c rsi_wlan_app.c main.c 

# SDK features
SDK_FEATURES = wlan ble bluetooth sockets certificates aws bleconfig 

include $(RSI_SDK_PATH)/sapi/sapi.mk
