# Make File
PROGNAME=tcp_logging_stats
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += -DLOGGING_STATS 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_wlan_tcp_logging_stats.c 

# SDK features
SDK_FEATURES = wlan sockets 

include $(RSI_SDK_PATH)/sapi/sapi.mk
