# Make File
PROGNAME=tcp_client_and_server
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_tcp_tx_and_rx.c 

# SDK features
SDK_FEATURES = wlan sockets certificates 

include $(RSI_SDK_PATH)/sapi/sapi.mk
