# Make File
PROGNAME=blood_pressure
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += -lm 
# Sources
APPLICATION_SOURCES = rsi_ble_blood_pressure.c 

# SDK features
SDK_FEATURES = ble bluetooth 

include $(RSI_SDK_PATH)/sapi/sapi.mk
