# Make File
PROGNAME=bt_sample_app
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_bt_sample_app.c 

# SDK features
SDK_FEATURES = bt sbc_audio bluetooth 

include $(RSI_SDK_PATH)/sapi/sapi.mk
