# Make File
PROGNAME=otaf
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ota_firmware_update_app.c 

# SDK features
SDK_FEATURES = wlan sockets 

include $(RSI_SDK_PATH)/sapi/sapi.mk
