# Make File
PROGNAME=gatt_long_read
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_ble_long_read.c 

# SDK features
SDK_FEATURES = bt ble bluetooth sbc_audio 

include $(RSI_SDK_PATH)/sapi/sapi.mk
