# Make File
PROGNAME=raw_data
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_raw_data_app.c 

# SDK features
SDK_FEATURES = wlan sockets 

include $(RSI_SDK_PATH)/sapi/sapi.mk
