# Make File
PROGNAME=aws_iot_mqtt
RSI_SDK_PATH = ../../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += -DMQTT_YIELD_EN 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_subscribe_publish_sample.c 

# SDK features
SDK_FEATURES = wlan sockets certificates aws 

include $(RSI_SDK_PATH)/sapi/sapi.mk
