# Make File
PROGNAME=http_otaf
RSI_SDK_PATH = ../../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Libraries
LIBS += 
# Sources
APPLICATION_SOURCES = rsi_http_otaf_app.c 

# SDK features
SDK_FEATURES = wlan sockets http_server certificates http_client firmware_update 

include $(RSI_SDK_PATH)/sapi/sapi.mk
